## YAML Template.
---
nomeAplicacao: Gambira (.yml producao)
mensagemUsuario: Vantagens ao utilizar o Gambira (.yml producao)
trancodes:
    -   codigo: 0001
        valor: LOGIN
    -   codigo: 0002
        valor: AUTENTICACAO
    